steps:
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: teched-apj02
    integrationFlowId: S0009720421-flow4
  integrationArtifactGetMplStatus:
    cpiApiServiceKeyCredentialsId: teched-apj02
    integrationFlowId: S0009720421-flow4
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: teched-apj02
    integrationFlowId: S0009720421-flow4
    integrationFlowName: S0009720421-flow4
    packageId: CICD
    filePath: S0009720421-IN180/S0009720421-flow4.zip
